---
title: "p8105_hw1_ob2305"
author: "Olya Besedina"
date: 2019-09-18
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
```

# Problem 1

```{r problem 1}

my_df = tibble(
  vec_numeric = rnorm(8),
  vec_logical = vec_numeric > 0,
  vec_char = c("monkey", "eel", "finch", "dog", "cat", "salmon", "carp","parrot"),
  vec_factor = factor(c("mammal", "fish", "bird", "mammal", "mammal", "fish", "fish", "bird"))
)

# The mean of the variables inside the data frame
mean(pull(my_df, vec_numeric))
mean(pull(my_df, vec_logical))
mean(pull(my_df, vec_char))
mean(pull(my_df, vec_factor))

# You can only take a mean of numeric or logical vectors, thus mean(vec_char) and mean(vec_factor) are not applicable.

## Application of as.numeric

# logical vector
l = pull(my_df, vec_logical)
as.numeric(l)

# character vector
c = pull(my_df, vec_char)
as.numeric(c)

# factor vector
f = pull(my_df, vec_factor)
as.numeric(f)
```

## Second code chunk

Convert logical vector to numeric and multiply result by the random sample
```{r eval=FALSE}
l = pull(my_df, vec_logical)
l_1 = as.numeric(l)
pull(my_df,vec_numeric)*l_1
```

Convert the logical vector to a factor and multiply teh random sample by the result
```{r eval=FALSE}
l_2 = pull(my_df, vec_logical)
l_3 = as.factor(l_2)
pull(my_df,vec_numeric)*l_3
```

Convert logical vector to a factor and then convert the result to numeric and multiply random sample by the result
```{r eval=FALSE}
l_2 = pull(my_df, vec_logical)
l_3 = as.factor(l_2)
l_4 = as.numeric(l_3)
pull(my_df,vec_numeric)*l_4
```


# Problem 2

```{r problem 2}
plot_df = tibble(
  x = rnorm(500),
  y = rnorm(500),
  logic_vector = (x + y) >1,
  numeric_vector = as.numeric(logic_vector)
)

```

